// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Unified KVP pool file backend for Hyper-V and Azure guests.
//!
//! All sizes are UTF-8 byte counts — the on-disk pool stores keys and
//! values as zero-padded UTF-8. The Windows-side Hyper-V wire spec is
//! UTF-16 char-based (256 / 1024), but the Linux `hv_kvp_daemon`
//! exchanges UTF-8 bytes with the kernel.
//!
//! Fixed-width record format (matches Linux kernel
//! `HV_KVP_EXCHANGE_MAX_*`):
//! - key field: 512 bytes
//! - value field: 2048 bytes
//! - record size: 2560 bytes
//!
//! [`PoolMode`] selects which size limits are enforced on writes:
//! - [`Safe`](PoolMode::Safe): key <= 254 bytes,
//!   value <= 1022 bytes (recommended for Linux kernel compatibility)
//! - [`Unsafe`](PoolMode::Unsafe): key <= 512 bytes, value <= 2048 bytes
//!
//! ## Reference
//! - [Hyper-V Data Exchange Service (KVP)](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/integration-services#hyper-v-data-exchange-service-kvp)

use std::collections::{HashMap, HashSet};
use std::fs::{File, OpenOptions};
use std::io::{self, ErrorKind, Read, Seek, Write};
use std::os::unix::fs::MetadataExt;
use std::os::unix::io::AsRawFd;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use sysinfo::System;

use crate::KvpError;

/// Default base directory for KVP pool files.
const DEFAULT_KVP_DIR: &str = "/var/lib/hyperv";

const WIRE_MAX_KEY_BYTES: usize = 512;
const WIRE_MAX_VALUE_BYTES: usize = 2048;
const SAFE_MAX_KEY_BYTES: usize = 254;
const SAFE_MAX_VALUE_BYTES: usize = 1022;

/// Maximum number of unique keys allowed in the pool.
const MAX_UNIQUE_KEYS: usize = 1024;

const RECORD_SIZE: usize = WIRE_MAX_KEY_BYTES + WIRE_MAX_VALUE_BYTES;

/// Hyper-V KVP pool indices.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum KvpPool {
    /// Host-to-guest data pushed by the host admin (`.kvp_pool_0`).
    External = 0,
    /// Guest-to-host data; cloud-init / azure-init write here (`.kvp_pool_1`).
    Guest = 1,
    /// Guest intrinsics generated by the daemon (`.kvp_pool_2`).
    Auto = 2,
    /// Host-originated data describing the host (`.kvp_pool_3`).
    AutoExternal = 3,
    /// Undocumented; no pool file exists (`.kvp_pool_4`).
    AutoInternal = 4,
}

impl KvpPool {
    /// Default base directory for KVP pool files.
    pub fn default_dir() -> &'static Path {
        Path::new(DEFAULT_KVP_DIR)
    }

    /// The conventional on-disk path (`/var/lib/hyperv/<pool_file>`).
    pub fn default_path(self) -> PathBuf {
        Self::default_dir().join(self.file_name())
    }

    /// File name of the pool file, e.g. `.kvp_pool_1`.
    pub fn file_name(self) -> &'static str {
        match self {
            Self::External => ".kvp_pool_0",
            Self::Guest => ".kvp_pool_1",
            Self::Auto => ".kvp_pool_2",
            Self::AutoExternal => ".kvp_pool_3",
            Self::AutoInternal => ".kvp_pool_4",
        }
    }
}

/// Policy mode controlling key/value size limits for writes.
///
/// All limits are **UTF-8 byte counts** measured against the on-disk
/// pool format. The Windows-side Hyper-V wire spec expresses limits
/// in UTF-16 code units (256 / 1024), which equal 512 / 2048 bytes
/// when stored as UTF-8 by `hv_kvp_daemon` on Linux.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PoolMode {
    /// Conservative limits for Linux kernel compatibility:
    /// key <= 254 UTF-8 bytes, value <= 1022 UTF-8 bytes — 2 bytes
    /// under the kernel `HV_KVP_EXCHANGE_MAX_*` maximums to leave room
    /// for a NUL terminator on either side of the boundary.
    Safe,
    /// Full Hyper-V wire-format limits expressed in UTF-8 bytes:
    /// key <= 512 bytes (== 256 UTF-16 code units),
    /// value <= 2048 bytes (== 1024 UTF-16 code units).
    Unsafe,
}

impl PoolMode {
    fn max_key_size(self) -> usize {
        match self {
            Self::Safe => SAFE_MAX_KEY_BYTES,
            Self::Unsafe => WIRE_MAX_KEY_BYTES,
        }
    }

    fn max_value_size(self) -> usize {
        match self {
            Self::Safe => SAFE_MAX_VALUE_BYTES,
            Self::Unsafe => WIRE_MAX_VALUE_BYTES,
        }
    }
}

/// Unified KVP pool file store.
#[derive(Clone, Debug)]
pub struct KvpPoolStore {
    pool: KvpPool,
    path: PathBuf,
    mode: PoolMode,
}

impl KvpPoolStore {
    /// Append a key-value pair without checking for an existing key.
    pub fn append(&self, key: &str, value: &str) -> Result<(), KvpError> {
        validate_key(key, self.mode.max_key_size())?;
        validate_value(value, self.mode.max_value_size())?;

        let mut iter = self.iter_mut()?;
        iter.append(key, value)?;
        iter.flush()?;
        Ok(())
    }

    /// Remove all entries from the store.
    pub fn clear(&self) -> Result<(), KvpError> {
        let file = match self.open_for_read_write() {
            Ok(f) => f,
            Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(()),
            Err(e) => return Err(e.into()),
        };

        lock_for_writing(&file)?;
        let write_result = file.set_len(0).map_err(KvpError::from);
        let unlock_result = unlock(&file).map_err(KvpError::from);
        write_result.and(unlock_result)
    }

    /// Clear the pool file if it contains data from a previous boot.
    pub fn clear_if_stale(&self) -> Result<(), KvpError> {
        if self.is_stale()? {
            self.clear()?;
        }
        Ok(())
    }

    /// Remove all records matching the key. Returns `true` if at least
    /// one record was present.
    pub fn delete(&self, key: &str) -> Result<bool, KvpError> {
        let file = match self.open_for_read_write() {
            Ok(f) => f,
            Err(ref e) if e.kind() == ErrorKind::NotFound => {
                return Ok(false);
            }
            Err(e) => return Err(e.into()),
        };

        let mut iter = KvpPoolIter::new(file, false)?;
        let mut found = false;
        while let Some(record) = iter.next() {
            let (k, _) = record?;
            if k == key {
                iter.remove_current()?;
                found = true;
            }
        }
        if found {
            iter.flush()?;
        }
        Ok(found)
    }

    /// Return all key-value records in on-disk order, including
    /// duplicates from [`append`](Self::append) calls.
    pub fn dump(&self) -> Result<Vec<(String, String)>, KvpError> {
        let mut iter = match self.iter() {
            Ok(it) => it,
            Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                return Ok(Vec::new());
            }
            Err(e) => return Err(e),
        };

        let mut records = Vec::with_capacity(iter.record_count());
        for record in iter.by_ref() {
            records.push(record?);
        }
        Ok(records)
    }

    /// Return all key-value pairs (deduplicated, last-write-wins).
    pub fn entries(&self) -> Result<HashMap<String, String>, KvpError> {
        let mut iter = match self.iter() {
            Ok(it) => it,
            Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                return Ok(HashMap::new());
            }
            Err(e) => return Err(e),
        };

        let mut map = HashMap::with_capacity(iter.record_count());
        for record in iter.by_ref() {
            let (k, v) = record?;
            map.insert(k, v);
        }
        Ok(map)
    }

    /// Insert a new key-value pair or update an existing key's value.
    pub fn insert(&self, key: &str, value: &str) -> Result<(), KvpError> {
        validate_key(key, self.mode.max_key_size())?;
        validate_value(value, self.mode.max_value_size())?;

        let mut iter = self.iter_mut()?;
        let mut found = false;
        let mut unique_keys = HashSet::new();

        // Continue past the first match to remove any duplicates
        // left by prior `append` calls so the upsert collapses to
        // a single record.
        while let Some(record) = iter.next() {
            let (k, _) = record?;
            let is_target = k == key;
            unique_keys.insert(k);
            if is_target {
                if !found {
                    iter.overwrite_current_value(value)?;
                    found = true;
                } else {
                    iter.remove_current()?;
                }
            }
        }

        if !found {
            if unique_keys.len() >= MAX_UNIQUE_KEYS {
                return Err(KvpError::MaxUniqueKeysExceeded {
                    max: MAX_UNIQUE_KEYS,
                });
            }
            iter.append(key, value)?;
        }

        iter.flush()?;
        Ok(())
    }

    /// Return whether the store is empty.
    pub fn is_empty(&self) -> Result<bool, KvpError> {
        Ok(self.len()? == 0)
    }

    /// Whether the store's data is stale (e.g. predates current boot).
    pub fn is_stale(&self) -> Result<bool, KvpError> {
        self.is_stale_at_boot(boot_time()?)
    }

    /// Variant of [`is_stale`](Self::is_stale) that takes an explicit
    /// boot time, allowing tests to assert against a deterministic
    /// reference point.
    fn is_stale_at_boot(&self, boot_time: i64) -> Result<bool, KvpError> {
        let metadata = match std::fs::metadata(&self.path) {
            Ok(m) => m,
            Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(false),
            Err(e) => return Err(e.into()),
        };
        Ok(metadata.mtime() < boot_time)
    }

    fn iter(&self) -> Result<KvpPoolIter, KvpError> {
        let file = self.open_for_read()?;
        KvpPoolIter::new(file, true)
    }

    fn iter_mut(&self) -> Result<KvpPoolIter, KvpError> {
        let file = self.open_for_read_write_create()?;
        KvpPoolIter::new(file, false)
    }

    /// Return the number of records in the store.
    ///
    /// This counts on-disk records, not unique keys. If
    /// [`append`](Self::append) was used to write duplicate keys, this
    /// may exceed the number of unique keys returned by
    /// [`entries`](Self::entries).
    pub fn len(&self) -> Result<usize, KvpError> {
        match std::fs::metadata(&self.path) {
            Ok(m) => Ok(m.len() as usize / RECORD_SIZE),
            Err(ref e) if e.kind() == ErrorKind::NotFound => Ok(0),
            Err(e) => Err(e.into()),
        }
    }

    /// Maximum key size in bytes for writes.
    pub fn max_key_size(&self) -> usize {
        self.mode.max_key_size()
    }

    /// Maximum value size in bytes for writes.
    pub fn max_value_size(&self) -> usize {
        self.mode.max_value_size()
    }

    /// The policy mode this store was created with.
    pub fn mode(&self) -> PoolMode {
        self.mode
    }

    /// Open using the default Hyper-V directory
    /// ([`/var/lib/hyperv`](KvpPool::default_dir)).
    pub fn new(pool: KvpPool, mode: PoolMode) -> Result<Self, KvpError> {
        Self::new_in(pool, KvpPool::default_dir(), mode)
    }

    /// Open using a custom directory (file name derived from `pool`).
    pub fn new_in(
        pool: KvpPool,
        dir: impl AsRef<Path>,
        mode: PoolMode,
    ) -> Result<Self, KvpError> {
        let path = dir.as_ref().join(pool.file_name());
        Ok(Self { pool, path, mode })
    }

    fn open_for_read(&self) -> io::Result<File> {
        OpenOptions::new().read(true).open(&self.path)
    }

    fn open_for_read_write(&self) -> io::Result<File> {
        OpenOptions::new().read(true).write(true).open(&self.path)
    }

    fn open_for_read_write_create(&self) -> io::Result<File> {
        OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(&self.path)
    }

    /// Return a reference to the pool file path.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The pool this store was created for.
    pub fn pool(&self) -> KvpPool {
        self.pool
    }

    /// Atomically replace all records with the given pairs, in
    /// iteration order. Inverse of [`dump`](Self::dump): duplicates
    /// are preserved, but unique-key count is capped at
    /// [`MAX_UNIQUE_KEYS`].
    ///
    /// Validation happens before locking, so a rejected batch never
    /// blocks other writers. The file is truncated and rewritten
    /// under one exclusive lock; an I/O error mid-write may leave
    /// the file partially written. Every successful call updates
    /// mtime (relevant to [`is_stale`](Self::is_stale)). Rejects
    /// malformed pool files (size not a multiple of the record
    /// size); call [`clear`](Self::clear) first to recover.
    pub fn populate<I, K, V>(&self, records: I) -> Result<(), KvpError>
    where
        I: IntoIterator<Item = (K, V)>,
        K: Into<String>,
        V: Into<String>,
    {
        let records: Vec<(String, String)> = records
            .into_iter()
            .map(|(k, v)| (k.into(), v.into()))
            .collect();

        let max_key = self.mode.max_key_size();
        let max_value = self.mode.max_value_size();
        let mut unique_keys = HashSet::new();
        for (k, v) in &records {
            validate_key(k, max_key)?;
            validate_value(v, max_value)?;
            unique_keys.insert(k.as_str());
        }
        if unique_keys.len() > MAX_UNIQUE_KEYS {
            return Err(KvpError::MaxUniqueKeysExceeded {
                max: MAX_UNIQUE_KEYS,
            });
        }

        let mut iter = self.iter_mut()?;
        iter.file.set_len(0)?;
        iter.record_count = 0;
        for (k, v) in &records {
            iter.append(k, v)?;
        }
        iter.flush()?;
        Ok(())
    }

    /// Read the value for a key. Returns `Ok(None)` when absent.
    ///
    /// If multiple records share the same key (e.g. via
    /// [`append`](Self::append)), the last (most recent) match wins.
    ///
    /// Unlike write operations, `read` does **not** enforce
    /// [`PoolMode`] key-size limits, so a [`Safe`](PoolMode::Safe)-mode
    /// store can read keys that were written in
    /// [`Unsafe`](PoolMode::Unsafe) mode.
    pub fn read(&self, key: &str) -> Result<Option<String>, KvpError> {
        let mut iter = match self.iter() {
            Ok(it) => it,
            Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                return Ok(None);
            }
            Err(e) => return Err(e),
        };

        let mut result = None;
        for record in iter.by_ref() {
            let (k, v) = record?;
            if k == key {
                result = Some(v);
            }
        }
        Ok(result)
    }
}

fn boot_time() -> Result<i64, KvpError> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock is before UNIX epoch")
        .as_secs();
    Ok(now.saturating_sub(System::uptime()) as i64)
}

fn decode_record(data: &[u8]) -> io::Result<(String, String)> {
    if data.len() != RECORD_SIZE {
        return Err(io::Error::other(format!(
            "record size mismatch: expected {RECORD_SIZE}, got {}",
            data.len()
        )));
    }

    let (key_bytes, value_bytes) = data.split_at(WIRE_MAX_KEY_BYTES);

    let key = std::str::from_utf8(key_bytes)
        .map_err(|e| io::Error::new(ErrorKind::InvalidData, e))?
        .trim_end_matches('\0')
        .to_string();
    let value = std::str::from_utf8(value_bytes)
        .map_err(|e| io::Error::new(ErrorKind::InvalidData, e))?
        .trim_end_matches('\0')
        .to_string();

    Ok((key, value))
}

fn encode_record(key: &str, value: &str) -> Vec<u8> {
    let mut buf = vec![0u8; RECORD_SIZE];

    let key_bytes = key.as_bytes();
    let key_len = key_bytes.len().min(WIRE_MAX_KEY_BYTES);
    buf[..key_len].copy_from_slice(&key_bytes[..key_len]);

    let value_bytes = value.as_bytes();
    let value_len = value_bytes.len().min(WIRE_MAX_VALUE_BYTES);
    buf[WIRE_MAX_KEY_BYTES..WIRE_MAX_KEY_BYTES + value_len]
        .copy_from_slice(&value_bytes[..value_len]);

    buf
}

// Locking: on Linux, take both `flock` and `fcntl` OFD locks together.
//
// Linux's `flock(2)` and `fcntl(2)` byte-range locks live in disjoint
// kernel domains. `hv_kvp_daemon` uses `fcntl`; cloud-init uses
// `flock(LOCK_EX)`. Hold both to coordinate with either.
//
// Acquire `flock` first, release `fcntl` first. The `fcntl` OFD
// variant (`F_OFD_SETLKW`) shares a domain with classic POSIX `fcntl`
// byte-range locks but is per-fd and thread-safe.
//

/// `flock(LOCK_EX)` then `fcntl(F_WRLCK)`. If `fcntl` fails, the
/// `flock` is released before returning the error.
fn lock_for_writing(file: &File) -> io::Result<()> {
    flock_lock_exclusive(file)?;
    if let Err(e) = fcntl_lock_exclusive(file) {
        let _ = flock_unlock(file);
        return Err(e);
    }
    Ok(())
}

/// `flock(LOCK_SH)` then `fcntl(F_RDLCK)`. See [`lock_for_writing`]
/// for the all-or-nothing semantics.
fn lock_for_reading(file: &File) -> io::Result<()> {
    flock_lock_shared(file)?;
    if let Err(e) = fcntl_lock_shared(file) {
        let _ = flock_unlock(file);
        return Err(e);
    }
    Ok(())
}

/// Release `fcntl` then `flock`. Both are attempted unconditionally;
/// the first error is returned.
fn unlock(file: &File) -> io::Result<()> {
    let fcntl_result = fcntl_unlock(file);
    let flock_result = flock_unlock(file);
    fcntl_result.and(flock_result)
}

/// Acquire an exclusive (write) `fcntl` OFD lock on the entire file.
fn fcntl_lock_exclusive(file: &File) -> io::Result<()> {
    let fl = libc::flock {
        l_type: libc::F_WRLCK as libc::c_short,
        l_whence: libc::SEEK_SET as libc::c_short,
        l_start: 0,
        l_len: 0,
        l_pid: 0,
    };
    if unsafe { libc::fcntl(file.as_raw_fd(), libc::F_OFD_SETLKW, &fl) } == -1 {
        return Err(io::Error::other(format!(
            "failed to fcntl-lock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a shared (read) `fcntl` OFD lock on the entire file.
fn fcntl_lock_shared(file: &File) -> io::Result<()> {
    let fl = libc::flock {
        l_type: libc::F_RDLCK as libc::c_short,
        l_whence: libc::SEEK_SET as libc::c_short,
        l_start: 0,
        l_len: 0,
        l_pid: 0,
    };
    if unsafe { libc::fcntl(file.as_raw_fd(), libc::F_OFD_SETLKW, &fl) } == -1 {
        return Err(io::Error::other(format!(
            "failed to fcntl-lock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Release the `fcntl` OFD lock on the entire file.
fn fcntl_unlock(file: &File) -> io::Result<()> {
    let fl = libc::flock {
        l_type: libc::F_UNLCK as libc::c_short,
        l_whence: libc::SEEK_SET as libc::c_short,
        l_start: 0,
        l_len: 0,
        l_pid: 0,
    };
    if unsafe { libc::fcntl(file.as_raw_fd(), libc::F_OFD_SETLK, &fl) } == -1 {
        return Err(io::Error::other(format!(
            "failed to fcntl-unlock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a `flock(LOCK_EX)` exclusive lock on the entire file.
fn flock_lock_exclusive(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a `flock(LOCK_SH)` shared lock on the entire file.
fn flock_lock_shared(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_SH) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Release the `flock` lock on the entire file.
fn flock_unlock(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_UN) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock-unlock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

fn validate_key(key: &str, max: usize) -> Result<(), KvpError> {
    if key.is_empty() {
        return Err(KvpError::EmptyKey);
    }
    if key.as_bytes().contains(&0) {
        return Err(KvpError::KeyContainsNull);
    }
    let actual = key.len();
    if actual > max {
        return Err(KvpError::KeyTooLarge { max, actual });
    }
    Ok(())
}

fn validate_value(value: &str, max: usize) -> Result<(), KvpError> {
    let actual = value.len();
    if actual > max {
        return Err(KvpError::ValueTooLarge { max, actual });
    }
    Ok(())
}

/// A record-at-a-time iterator over a KVP pool file.
///
/// Uses file I/O with seek semantics for memory-efficient iteration
/// without loading all records into memory. Supports in-place value
/// overwrites and record removal for the last-yielded record.
///
/// The underlying file is locked in [`new`](Self::new); both the lock
/// release and the `close(2)` happen via [`Drop`], with unlock issued
/// before the file's own drop closes the fd. Unlock errors in the
/// drop path are unrecoverable and silently discarded — `close(2)`
/// would release any still-held locks as a backstop.
#[derive(Debug)]
struct KvpPoolIter {
    file: File,
    record_count: usize,
    current_index: usize,
}

impl Drop for KvpPoolIter {
    fn drop(&mut self) {
        // Drop runs before fields are dropped, so `self.file` is still
        // a valid open fd here. Errors are unrecoverable in Drop;
        // close(2) on the subsequent field drop releases any
        // still-held locks regardless.
        let _ = unlock(&self.file);
    }
}

impl KvpPoolIter {
    /// Append a new record at the end of the file, zero-padded to the
    /// fixed-width wire format.
    fn append(&mut self, key: &str, value: &str) -> io::Result<()> {
        let pos = self.file.seek(io::SeekFrom::End(0))?;
        debug_assert!((pos as usize).is_multiple_of(RECORD_SIZE));
        self.file.write_all(&encode_record(key, value))?;
        self.record_count += 1;
        Ok(())
    }

    /// Flush any buffered writes to the underlying file.
    fn flush(&mut self) -> io::Result<()> {
        self.file.flush()
    }

    fn new(mut file: File, read_only: bool) -> Result<Self, KvpError> {
        if read_only {
            lock_for_reading(&file)?;
        } else {
            lock_for_writing(&file)?;
        }

        let len = file.metadata()?.len() as usize;
        if len > 0 && !len.is_multiple_of(RECORD_SIZE) {
            return Err(io::Error::other(format!(
                "file size ({len}) is not a multiple of record size \
                 ({RECORD_SIZE})"
            ))
            .into());
        }

        let record_count = len / RECORD_SIZE;
        file.seek(io::SeekFrom::Start(0))?;

        Ok(Self {
            file,
            record_count,
            current_index: 0,
        })
    }

    /// Overwrite the value field of the record last returned by
    /// [`next()`](Iterator::next), zero-padding to fill the
    /// fixed-width 2048-byte field.
    ///
    /// After the write the file position is at the start of the next
    /// record, so iteration can continue normally.
    ///
    /// Returns `InvalidInput` if called before the first `next()`.
    fn overwrite_current_value(&mut self, value: &str) -> io::Result<()> {
        if self.current_index == 0 {
            return Err(io::Error::new(
                ErrorKind::InvalidInput,
                "no record has been read yet",
            ));
        }

        let record_start = (self.current_index - 1) as u64 * RECORD_SIZE as u64;
        let value_offset = record_start + WIRE_MAX_KEY_BYTES as u64;

        self.file.seek(io::SeekFrom::Start(value_offset))?;

        let mut buf = [0u8; WIRE_MAX_VALUE_BYTES];
        let bytes = value.as_bytes();
        let len = bytes.len().min(WIRE_MAX_VALUE_BYTES);
        buf[..len].copy_from_slice(&bytes[..len]);

        self.file.write_all(&buf)?;
        Ok(())
    }

    /// The number of records in the file (updated by
    /// [`append`](Self::append) and
    /// [`remove_current`](Self::remove_current)).
    fn record_count(&self) -> usize {
        self.record_count
    }

    /// Remove the record last returned by [`next()`](Iterator::next)
    /// by swapping it with the final record and truncating the file.
    ///
    /// After removal the file position rewinds so that the next call
    /// to `next()` reads the record that was swapped into this slot
    /// (unless the removed record was already the last one).
    ///
    /// Returns `InvalidInput` if called before the first `next()`.
    fn remove_current(&mut self) -> io::Result<()> {
        if self.current_index == 0 {
            return Err(io::Error::new(
                ErrorKind::InvalidInput,
                "no record has been read yet",
            ));
        }

        let delete_index = self.current_index - 1;
        let last_index = self.record_count - 1;

        if delete_index != last_index {
            self.file.seek(io::SeekFrom::Start(
                last_index as u64 * RECORD_SIZE as u64,
            ))?;
            let mut buf = [0u8; RECORD_SIZE];
            self.file.read_exact(&mut buf)?;

            self.file.seek(io::SeekFrom::Start(
                delete_index as u64 * RECORD_SIZE as u64,
            ))?;
            self.file.write_all(&buf)?;

            // Rewind so the next `next()` re-reads `delete_index`,
            // which now holds the swapped-in record. `write_all`
            // advanced the cursor past it, hence this third seek.
            self.file.seek(io::SeekFrom::Start(
                delete_index as u64 * RECORD_SIZE as u64,
            ))?;
            self.current_index = delete_index;
        }
        // No-swap branch: `current_index` is left at the old
        // `record_count`, so after the truncate below the iterator
        // is naturally exhausted and the next `next()` returns None.

        self.file.set_len(last_index as u64 * RECORD_SIZE as u64)?;
        self.record_count -= 1;
        Ok(())
    }

}

impl Iterator for KvpPoolIter {
    type Item = io::Result<(String, String)>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.current_index >= self.record_count {
            return None;
        }
        let mut buf = [0u8; RECORD_SIZE];
        match self.file.read_exact(&mut buf) {
            Ok(()) => {
                self.current_index += 1;
                Some(decode_record(&buf))
            }
            Err(e) => Some(Err(e)),
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.record_count - self.current_index;
        (remaining, Some(remaining))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;
    use std::error::Error;
    use std::os::unix::fs::PermissionsExt;
    use tempfile::{NamedTempFile, TempDir};

    fn safe_store(dir: &Path) -> KvpPoolStore {
        KvpPoolStore::new_in(KvpPool::Guest, dir, PoolMode::Safe).unwrap()
    }

    fn unsafe_store(dir: &Path) -> KvpPoolStore {
        KvpPoolStore::new_in(KvpPool::Guest, dir, PoolMode::Unsafe).unwrap()
    }

    /// `&str` literals → `Vec<(String, String)>` for `dump`/`populate`.
    fn pairs<const N: usize>(
        items: [(&str, &str); N],
    ) -> Vec<(String, String)> {
        items
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    /// Bulk-load `count` records (`k0..k{count-1}` → `"v"`) for tests
    /// that need to set up at or near [`MAX_UNIQUE_KEYS`].
    fn prepopulate(store: &KvpPoolStore, count: usize) {
        let records: Vec<(String, String)> = (0..count)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        store.populate(records).unwrap();
    }

    fn lock_dir(dir: &Path) {
        std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o000))
            .unwrap();
    }

    fn unlock_dir(dir: &Path) {
        std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o755))
            .unwrap();
    }

    fn set_mtime_to_epoch(path: &Path) {
        let c_path =
            std::ffi::CString::new(path.as_os_str().as_encoded_bytes())
                .unwrap();
        let times = [libc::timeval {
            tv_sec: 0,
            tv_usec: 0,
        }; 2];
        assert_eq!(unsafe { libc::utimes(c_path.as_ptr(), times.as_ptr()) }, 0);
    }

    #[test]
    fn test_kvp_pool_file_names() {
        assert_eq!(KvpPool::External.file_name(), ".kvp_pool_0");
        assert_eq!(KvpPool::Guest.file_name(), ".kvp_pool_1");
        assert_eq!(KvpPool::Auto.file_name(), ".kvp_pool_2");
        assert_eq!(KvpPool::AutoExternal.file_name(), ".kvp_pool_3");
        assert_eq!(KvpPool::AutoInternal.file_name(), ".kvp_pool_4");
    }

    #[test]
    fn test_kvp_pool_default_dir_and_path() {
        assert_eq!(KvpPool::default_dir(), Path::new("/var/lib/hyperv"));
        assert_eq!(
            KvpPool::Guest.default_path(),
            Path::new("/var/lib/hyperv/.kvp_pool_1")
        );
    }

    #[test]
    fn test_default_path_is_used() {
        let store = KvpPoolStore::new(KvpPool::Guest, PoolMode::Safe).unwrap();
        assert_eq!(store.path(), KvpPool::Guest.default_path());
    }

    #[test]
    fn test_new_in_derives_path_from_pool() {
        let dir = TempDir::new().unwrap();
        let store =
            KvpPoolStore::new_in(KvpPool::Guest, dir.path(), PoolMode::Safe)
                .unwrap();
        assert_eq!(store.path(), dir.path().join(KvpPool::Guest.file_name()));
    }

    #[test]
    fn test_pool_getter() {
        let store =
            KvpPoolStore::new(KvpPool::External, PoolMode::Safe).unwrap();
        assert_eq!(store.pool(), KvpPool::External);
    }

    #[test]
    fn test_mode_getter() {
        let dir = TempDir::new().unwrap();
        let store_safe = safe_store(dir.path());
        assert_eq!(store_safe.mode(), PoolMode::Safe);

        let dir2 = TempDir::new().unwrap();
        let store_unsafe = unsafe_store(dir2.path());
        assert_eq!(store_unsafe.mode(), PoolMode::Unsafe);
    }

    #[test]
    fn test_max_key_size() {
        let dir = TempDir::new().unwrap();
        assert_eq!(safe_store(dir.path()).max_key_size(), 254);

        let dir2 = TempDir::new().unwrap();
        assert_eq!(unsafe_store(dir2.path()).max_key_size(), 512);
    }

    #[test]
    fn test_max_value_size() {
        let dir = TempDir::new().unwrap();
        assert_eq!(safe_store(dir.path()).max_value_size(), 1022);

        let dir2 = TempDir::new().unwrap();
        assert_eq!(unsafe_store(dir2.path()).max_value_size(), 2048);
    }

    #[test]
    fn test_insert_rejects_empty_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let err = store.insert("", "value").unwrap_err();
        assert!(matches!(err, KvpError::EmptyKey));
    }

    #[test]
    fn test_insert_rejects_null_in_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let err = store.insert("bad\0key", "value").unwrap_err();
        assert!(matches!(err, KvpError::KeyContainsNull));
    }

    #[derive(Clone, Copy)]
    enum Field {
        Key,
        Value,
    }

    #[derive(Clone, Copy)]
    enum Op {
        Insert,
        Append,
    }

    /// For each `(PoolMode, Op, Field)`, accept `max` and reject `max + 1`.
    #[rstest]
    #[case::safe_insert_key(PoolMode::Safe, Op::Insert, Field::Key, 254)]
    #[case::safe_insert_value(PoolMode::Safe, Op::Insert, Field::Value, 1022)]
    #[case::safe_append_key(PoolMode::Safe, Op::Append, Field::Key, 254)]
    #[case::safe_append_value(PoolMode::Safe, Op::Append, Field::Value, 1022)]
    #[case::unsafe_insert_key(PoolMode::Unsafe, Op::Insert, Field::Key, 512)]
    #[case::unsafe_insert_value(
        PoolMode::Unsafe,
        Op::Insert,
        Field::Value,
        2048
    )]
    #[case::unsafe_append_key(PoolMode::Unsafe, Op::Append, Field::Key, 512)]
    #[case::unsafe_append_value(
        PoolMode::Unsafe,
        Op::Append,
        Field::Value,
        2048
    )]
    fn test_size_limits(
        #[case] mode: PoolMode,
        #[case] op: Op,
        #[case] field: Field,
        #[case] max: usize,
    ) {
        let dir = TempDir::new().unwrap();
        let store =
            KvpPoolStore::new_in(KvpPool::Guest, dir.path(), mode).unwrap();

        let write = |store: &KvpPoolStore, k: &str, v: &str| match op {
            Op::Insert => store.insert(k, v),
            Op::Append => store.append(k, v),
        };

        match field {
            Field::Key => {
                write(&store, &"k".repeat(max), "v").unwrap();
                let err = write(&store, &"k".repeat(max + 1), "v").unwrap_err();
                assert!(matches!(err, KvpError::KeyTooLarge { .. }));
            }
            Field::Value => {
                write(&store, "k", &"v".repeat(max)).unwrap();
                let err =
                    write(&store, "k2", &"v".repeat(max + 1)).unwrap_err();
                assert!(matches!(err, KvpError::ValueTooLarge { .. }));
            }
        }
    }

    #[test]
    fn test_read_accepts_wire_max_key_in_safe_mode() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let store_unsafe = unsafe_store(dir.path());
        let long_key = "k".repeat(300);
        store_unsafe.insert(&long_key, "val").unwrap();

        assert_eq!(store.read(&long_key).unwrap(), Some("val".to_string()));

        let too_long = "k".repeat(513);
        assert_eq!(store.read(&too_long).unwrap(), None);
    }

    #[test]
    fn test_insert_overwrites_existing_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("key", "v1"), ("other", "v3")]))
            .unwrap();
        store.insert("key", "v2").unwrap();

        assert_eq!(
            store.dump().unwrap(),
            pairs([("key", "v2"), ("other", "v3")])
        );
    }

    #[test]
    fn test_insert_file_size_unchanged_on_overwrite() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.insert("key", "original").unwrap();
        let size_before = std::fs::metadata(store.path()).unwrap().len();

        store.insert("key", "updated").unwrap();
        let size_after = std::fs::metadata(store.path()).unwrap().len();

        assert_eq!(size_before, size_after);
        assert_eq!(store.read("key").unwrap(), Some("updated".to_string()));
    }

    #[test]
    fn test_insert_file_size_grows_on_new_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.insert("k1", "v1").unwrap();
        let size_before = std::fs::metadata(store.path()).unwrap().len();

        store.insert("k2", "v2").unwrap();
        let size_after = std::fs::metadata(store.path()).unwrap().len();

        assert_eq!(size_after - size_before, RECORD_SIZE as u64);
    }

    #[test]
    fn test_insert_preserves_other_records() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        for i in 0..5 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let raw_before = std::fs::read(store.path()).unwrap();
        store.insert("k2", "CHANGED").unwrap();
        let raw_after = std::fs::read(store.path()).unwrap();

        assert_eq!(raw_before.len(), raw_after.len());
        for i in 0..5 {
            if i == 2 {
                continue;
            }
            let start = i * RECORD_SIZE;
            let end = start + RECORD_SIZE;
            assert_eq!(&raw_before[start..end], &raw_after[start..end]);
        }
    }

    #[test]
    fn test_insert_after_append_duplicates_collapses_to_one() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("k", "v1"), ("k", "v2"), ("k", "v3")]))
            .unwrap();

        store.insert("k", "updated").unwrap();
        assert_eq!(store.dump().unwrap(), pairs([("k", "updated")]));
    }

    #[test]
    fn test_unique_key_cap_allows_1024_then_rejects_1025th() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        let err = store.insert("overflow", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));
    }

    #[test]
    fn test_unique_key_cap_allows_overwrite_at_limit() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        store.insert("k0", "updated").unwrap();
        assert_eq!(store.read("k0").unwrap(), Some("updated".to_string()));
    }

    #[test]
    fn test_insert_cap_uses_unique_keys_not_record_count() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS - 1);

        store.append("k0", "dup").unwrap();
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        store.insert("new_unique", "v").unwrap();
        assert_eq!(store.read("new_unique").unwrap(), Some("v".to_string()));
    }

    #[test]
    fn test_unique_key_cap_allows_new_key_after_delete() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        assert!(store.delete("k0").unwrap());
        store.insert("new-key", "v").unwrap();
    }

    #[test]
    fn test_append_no_key_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        store.append("extra", "val").unwrap();
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS + 1);
    }

    #[test]
    fn test_append_then_read() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("diag_001", "event_data").unwrap();
        assert_eq!(
            store.read("diag_001").unwrap(),
            Some("event_data".to_string())
        );
    }

    #[test]
    fn test_append_duplicate_key_semantics() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("X", "first").unwrap();
        store.append("X", "second").unwrap();

        assert_eq!(
            store.dump().unwrap(),
            pairs([("X", "first"), ("X", "second")])
        );
        assert_eq!(store.read("X").unwrap(), Some("second".to_string()));
    }

    #[test]
    fn test_read_missing_file_returns_none() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert_eq!(store.read("anything").unwrap(), None);
    }

    #[test]
    fn test_delete_removes_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("key", "v1"), ("other", "v2")]))
            .unwrap();

        assert!(store.delete("key").unwrap());
        assert_eq!(store.dump().unwrap(), pairs([("other", "v2")]));
    }

    #[test]
    fn test_delete_removes_all_duplicates() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("k", "v1"),
                ("other", "x"),
                ("k", "v2"),
                ("k", "v3"),
            ]))
            .unwrap();

        assert!(store.delete("k").unwrap());
        assert_eq!(store.dump().unwrap(), pairs([("other", "x")]));
    }

    #[test]
    fn test_delete_middle_record_swaps_with_last() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("k0", "v"),
                ("k1", "v"),
                ("k2", "v"),
                ("k3", "v"),
                ("k4", "v"),
                ("k5", "v"),
                ("k6", "v"),
                ("k7", "v"),
                ("k8", "v"),
                ("k9", "v"),
            ]))
            .unwrap();

        assert!(store.delete("k4").unwrap());

        // k9 takes k4's slot; the rest stays put.
        assert_eq!(
            store.dump().unwrap(),
            pairs([
                ("k0", "v"),
                ("k1", "v"),
                ("k2", "v"),
                ("k3", "v"),
                ("k9", "v"),
                ("k5", "v"),
                ("k6", "v"),
                ("k7", "v"),
                ("k8", "v"),
            ])
        );
    }

    /// Exposes a bug where `remove_current()` reorders duplicate
    /// records via its swap-with-last strategy, silently changing
    /// which duplicate `entries()` reports as last-write-wins.
    ///
    /// Initial on-disk order has `("dup", "C")` as the final record
    /// for key `"dup"`, so `entries()["dup"] == "C"`. After deleting
    /// the unrelated `"middle"` key, the swap moves `("dup", "C")`
    /// into the freed slot ahead of `("dup", "B")`, leaving `"B"` as
    /// the on-disk-last record for `"dup"`.
    #[test]
    fn test_delete_reorders_duplicates_breaking_last_write_wins() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("dup", "A"),
                ("middle", "m"),
                ("dup", "B"),
                ("other", "x"),
                ("dup", "C"),
            ]))
            .unwrap();

        assert_eq!(
            store.entries().unwrap().get("dup"),
            Some(&"C".to_string()),
            "precondition: last-write-wins picks the final on-disk record",
        );

        assert!(store.delete("middle").unwrap());

        assert_eq!(
            store.dump().unwrap(),
            pairs([
                ("dup", "A"),
                ("dup", "B"),
                ("other", "x"),
                ("dup", "C"),
            ]),
            "deleting an unrelated key must preserve the relative order \
             of every other record (so last-write-wins still picks C \
             for `dup`)",
        );
        assert_eq!(
            store.entries().unwrap().get("dup"),
            Some(&"C".to_string()),
            "deleting an unrelated key must not change which duplicate \
             entries() reports as the winning value",
        );
    }

    /// Companion to
    /// [`test_delete_reorders_duplicates_breaking_last_write_wins`]
    /// for the other production caller of `remove_current()`: the
    /// duplicate-collapsing branch of [`KvpPoolStore::insert`].
    ///
    /// Initial on-disk order has `("dup", "C")` as the final record
    /// for key `"dup"`, so `entries()["dup"] == "C"`. Inserting
    /// `"ins"` overwrites the first `"ins"` record in place and then
    /// calls `remove_current()` on the second `"ins"`, which swaps
    /// the tail `("dup", "C")` forward of `("dup", "B")`, leaving
    /// `"B"` as the on-disk-last record for `"dup"`.
    #[test]
    fn test_insert_reorders_duplicates_breaking_last_write_wins() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("ins", "i1"),
                ("ins", "i2"),
                ("dup", "B"),
                ("dup", "C"),
            ]))
            .unwrap();

        assert_eq!(
            store.entries().unwrap().get("dup"),
            Some(&"C".to_string()),
            "precondition: last-write-wins picks the final on-disk record",
        );

        store.insert("ins", "new").unwrap();

        assert_eq!(
            store.dump().unwrap(),
            pairs([("ins", "new"), ("dup", "B"), ("dup", "C")]),
            "collapsing duplicate `ins` records must preserve the \
             relative order of unrelated `dup` records (so last-write-wins \
             still picks C for `dup`)",
        );
        assert_eq!(
            store.entries().unwrap().get("dup"),
            Some(&"C".to_string()),
            "insert collapsing its own duplicates must not change which \
             duplicate of an unrelated key entries() reports as winning",
        );
    }

    /// Exposes a silent data-corruption bug in the value round-trip:
    /// trailing null bytes in user-supplied values are indistinguishable
    /// from the zero-padding that fills the fixed-width 2048-byte value
    /// field, so [`decode_record`]'s `trim_end_matches('\0')` strips
    /// them on read.
    ///
    /// [`validate_key`] rejects null bytes in keys, preventing this for
    /// the key field, but [`validate_value`] performs no equivalent
    /// check, so a write like `insert("k", "data\0")` succeeds and
    /// silently round-trips as `"data"`.
    ///
    /// Embedded (non-trailing) null bytes are preserved because `trim`
    /// only strips the suffix; only trailing nulls are lost.
    #[test]
    fn test_value_with_trailing_null_round_trips() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // Embedded null in the middle is preserved (sanity check).
        store.insert("embedded", "a\0b").unwrap();
        assert_eq!(
            store.read("embedded").unwrap(),
            Some("a\0b".to_string()),
            "embedded null bytes must round-trip unchanged",
        );

        // Trailing null is silently stripped by trim_end_matches('\0').
        store.insert("trailing", "data\0").unwrap();
        assert_eq!(
            store.read("trailing").unwrap(),
            Some("data\0".to_string()),
            "trailing null bytes in a value must round-trip unchanged \
             (or `validate_value` should reject them, mirroring \
             `validate_key`'s null-byte rejection)",
        );
    }

    /// `len()` and `is_empty()` use `metadata().len()` directly without
    /// going through [`KvpPoolIter::new`], which silently rounds down
    /// for files whose size isn't a multiple of [`RECORD_SIZE`]. Other
    /// operations (`iter()`, `dump()`, `read()`, ...) reject the same
    /// file with [`KvpError::Io`], so the corruption is observable
    /// through one API but invisible through another.
    #[test]
    fn test_len_and_is_empty_mask_corrupt_file_size() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // Write 1.5 records' worth of bytes — a clearly corrupt file.
        std::fs::write(store.path(), vec![0u8; RECORD_SIZE + 100]).unwrap();

        // dump/read/entries all reject this file as malformed.
        assert!(store.dump().is_err());

        // len/is_empty silently round down and report a partial record
        // count, hiding the corruption that other operations expose.
        assert!(
            store.len().is_err(),
            "len() must reject a malformed file rather than silently \
             rounding down (other ops do reject it; len() must be \
             consistent)",
        );
        assert!(
            store.is_empty().is_err(),
            "is_empty() must reject a malformed file rather than \
             reporting `false` based on a rounded-down record count",
        );
    }

    /// `KvpPoolIter::flush` calls `File::flush`, which is a documented
    /// no-op for unbuffered `File` handles. Writes return `Ok(())`
    /// while the data still lives only in the kernel page cache, so a
    /// power loss between `insert(...)` returning and the kernel's
    /// next writeback silently drops the write. The method should
    /// call `sync_data()` (or `sync_all()`) to actually persist.
    ///
    /// Hard to assert at the file-system level from a unit test; this
    /// test pins the misleading API by demonstrating that flush()
    /// completes even on a read-only fd, which it could not do if it
    /// performed any real I/O.
    #[test]
    fn test_flush_is_a_no_op_not_a_real_sync() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k", "v").unwrap();

        // Open read-only and try to flush; a real fsync would fail
        // with EBADF on a read-only fd, but File::flush is a no-op.
        let file = OpenOptions::new().read(true).open(store.path()).unwrap();
        let result = (&file).flush();
        assert!(
            result.is_err(),
            "iter.flush() ultimately calls File::flush, which is a \
             no-op and silently succeeds even when no real sync \
             happened — replace with sync_data() if writes are \
             expected to be durable across crashes",
        );
    }

    /// Newly-created pool files inherit the process umask and are
    /// usually world-readable (0644 or 0664). The pool may carry
    /// guest-host KVP data that shouldn't be readable by unprivileged
    /// users; `open_for_read_write_create` should `OpenOptions::mode`
    /// the file to 0600 (or another tight mode) on creation.
    #[test]
    fn test_created_pool_file_has_too_permissive_mode() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // Triggers create-on-open via iter_mut().
        store.insert("k", "v").unwrap();

        let mode = std::fs::metadata(store.path()).unwrap().mode() & 0o777;
        assert_eq!(
            mode, 0o600,
            "newly-created pool file should be mode 0600 to prevent \
             unprivileged readers from observing KVP traffic; got \
             {mode:o} (default umask-derived mode is too permissive)",
        );
    }

    /// `populate(empty)` on a store whose file does not yet exist
    /// silently creates a 0-byte file via `iter_mut`'s implicit
    /// `create(true)`. There is no "empty an already-empty store"
    /// concept that requires this side effect, and littering
    /// `/var/lib/hyperv` with stub files is surprising.
    #[test]
    fn test_populate_empty_does_not_create_missing_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        assert!(!store.path().exists(), "precondition");

        store.populate(Vec::<(String, String)>::new()).unwrap();

        assert!(
            !store.path().exists(),
            "populate(empty) on a missing file should be a no-op, not \
             create a 0-byte stub",
        );
    }

    /// Read operations (`read`, `delete`) silently accept inputs that
    /// the write side rejects — empty strings and strings containing
    /// null bytes. They iterate the file looking for an exact match
    /// that can never exist (because writes reject those inputs),
    /// returning `None`/`false` instead of surfacing the obvious
    /// programmer error. Inconsistent with `insert`/`append`.
    #[test]
    fn test_read_accepts_inputs_that_write_rejects() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k", "v").unwrap();

        // Write side: empty key is an error.
        assert!(matches!(
            store.insert("", "v").unwrap_err(),
            KvpError::EmptyKey
        ));
        // Read side: empty key is silently accepted as "not found".
        assert!(
            store.read("").is_err(),
            "read(\"\") should error with EmptyKey, mirroring write \
             validation, not silently return None",
        );

        // Write side: null in key is an error.
        assert!(matches!(
            store.insert("a\0b", "v").unwrap_err(),
            KvpError::KeyContainsNull
        ));
        // Read side: null in key is silently accepted.
        assert!(
            store.read("a\0b").is_err(),
            "read(\"a\\0b\") should error with KeyContainsNull, \
             mirroring write validation",
        );

        // Same for delete.
        assert!(
            store.delete("").is_err(),
            "delete(\"\") should error with EmptyKey",
        );
    }

    /// `KvpPoolStore::populate` builds a `HashSet<&str>` for the
    /// unique-key cap check. The set borrows from `records: Vec<(String,
    /// String)>`, so the set's len reflects unique inputs — but the
    /// validation loop also calls `validate_value` for every record,
    /// including duplicates of the same key. With many duplicates
    /// `populate` does O(N) extra validation work. Performance, not
    /// correctness — but it pairs with a real correctness gap: the
    /// unique-key cap counts the *input* uniques, not the *resulting*
    /// uniques, so a populate that intentionally drops a duplicate
    /// (e.g. via dedup-after-populate logic the caller might add)
    /// would over-count. Confirm the documented "unique-key cap is
    /// inputs" semantics here so any future change has to update this
    /// test deliberately.
    #[test]
    fn test_populate_cap_counts_input_uniques_not_record_count() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // 2 records, 1 unique key. Cap is on uniques, so this
        // succeeds even with MAX_UNIQUE_KEYS - 1 *other* unique
        // keys in the same batch.
        let mut records: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS - 1)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        records.push(("dup".to_string(), "a".to_string()));
        records.push(("dup".to_string(), "b".to_string()));
        // unique input keys = MAX_UNIQUE_KEYS, total records =
        // MAX_UNIQUE_KEYS + 1. Allowed because uniques == cap.
        store.populate(records).unwrap();
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS + 1);
    }

    /// `KvpPoolStore::clear_if_stale` checks staleness then clears as
    /// two separate locked operations. Between the `is_stale` stat
    /// and the `clear` open, another writer can append fresh data —
    /// which `clear_if_stale` then deletes. The check-then-act should
    /// be performed under a single exclusive lock.
    ///
    /// This test demonstrates the race deterministically by calling
    /// the inner check and the inner clear sequentially with an
    /// interleaved write, simulating the worst-case TOCTOU window.
    #[test]
    fn test_clear_if_stale_toctou_loses_concurrent_write() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // Stale data on disk.
        store.insert("old", "value").unwrap();
        set_mtime_to_epoch(store.path());
        assert!(store.is_stale().unwrap(), "precondition: stale");

        // Race window: another writer commits fresh data after the
        // stale check but before the clear runs.
        let was_stale = store.is_stale().unwrap();
        store.insert("fresh", "just_written").unwrap();
        if was_stale {
            store.clear().unwrap();
        }

        assert_eq!(
            store.read("fresh").unwrap(),
            Some("just_written".to_string()),
            "freshly-written data must survive clear_if_stale; the \
             stale check and the clear must hold the same exclusive \
             lock so a writer cannot slip data in between them",
        );
    }

    /// `boot_time()` mixes clock domains: `SystemTime::now()` reads
    /// `CLOCK_REALTIME` while `sysinfo::System::uptime()` is sourced
    /// from a monotonic boot clock. NTP adjustments, manual clock
    /// changes, or DST jumps to `CLOCK_REALTIME` make the computed
    /// "boot time" drift, which makes [`KvpPoolStore::is_stale`]
    /// either falsely report stale (after a clock backwards-jump) or
    /// falsely report fresh (after a clock forward-jump). Boot time
    /// should be read from `/proc/stat`'s `btime` field, which is
    /// the canonical kernel-recorded value and is not affected by
    /// clock adjustments.
    ///
    /// Hard to assert without time mocking; this test documents the
    /// expectation that two consecutive boot_time() calls within a
    /// single second return the same value (which they currently do
    /// only by accident of second-resolution truncation).
    #[test]
    fn test_boot_time_is_stable_across_calls() {
        let a = boot_time().unwrap();
        let b = boot_time().unwrap();
        // Currently passes by accident (both calls happen within the
        // same second), but a real fix should read btime once and
        // cache it, or at minimum document the clock-skew sensitivity.
        assert_eq!(
            a, b,
            "boot_time() should be a stable kernel-recorded value, \
             not a SystemTime/uptime arithmetic that drifts under \
             NTP correction",
        );
    }

    #[test]
    fn test_delete_missing_file_returns_false() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(!store.delete("anything").unwrap());
    }

    #[test]
    fn test_delete_nonexistent_key_returns_false() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k1", "v1").unwrap();

        assert!(!store.delete("missing").unwrap());
        assert_eq!(store.len().unwrap(), 1);
    }

    #[test]
    fn test_clear_empties_store() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.insert("key", "value").unwrap();
        store.clear().unwrap();
        assert_eq!(store.read("key").unwrap(), None);
    }

    #[test]
    fn test_clear_missing_file_is_ok() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.clear().unwrap();
    }

    #[test]
    fn test_entries_missing_file_returns_empty() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(store.entries().unwrap().is_empty());
    }

    #[test]
    fn test_dump_returns_all_records_with_duplicates() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records =
            pairs([("key", "val1"), ("key", "val2"), ("key", "val3")]);
        store.populate(records.clone()).unwrap();

        assert_eq!(store.dump().unwrap(), records);
        assert_eq!(
            store.entries().unwrap().get("key"),
            Some(&"val3".to_string())
        );
    }

    #[test]
    fn test_dump_missing_file_returns_empty() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(store.dump().unwrap().is_empty());
    }

    #[test]
    fn test_populate_round_trips_with_dump() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records =
            pairs([("a", "1"), ("b", "2"), ("a", "3"), ("c", "4"), ("b", "5")]);
        store.populate(records.clone()).unwrap();
        assert_eq!(store.dump().unwrap(), records);
    }

    #[test]
    fn test_populate_truncates_prior_contents() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("old1", "v").unwrap();
        store.append("old2", "v").unwrap();
        store.append("old3", "v").unwrap();
        assert_eq!(store.len().unwrap(), 3);

        store.populate(pairs([("new", "only")])).unwrap();
        assert_eq!(store.dump().unwrap(), pairs([("new", "only")]));
    }

    #[test]
    fn test_populate_empty_clears_store() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("k", "v").unwrap();
        store.populate(Vec::<(String, String)>::new()).unwrap();
        assert!(store.is_empty().unwrap());
    }

    #[test]
    fn test_populate_validates_before_writing() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("keep", "me")])).unwrap();

        // Bad record mid-batch: file must be untouched on rejection.
        let bad_value = "v".repeat(1023);
        let err = store
            .populate(vec![
                ("a".to_string(), "1".to_string()),
                ("b".to_string(), bad_value),
                ("c".to_string(), "3".to_string()),
            ])
            .unwrap_err();
        assert!(matches!(err, KvpError::ValueTooLarge { .. }));

        assert_eq!(store.dump().unwrap(), pairs([("keep", "me")]));
    }

    #[test]
    fn test_populate_rejects_empty_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let err = store.populate(pairs([("", "v")])).unwrap_err();
        assert!(matches!(err, KvpError::EmptyKey));
    }

    #[test]
    fn test_populate_enforces_unique_key_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let too_many: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS + 1)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        let err = store.populate(too_many).unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));

        // Cap is checked pre-lock; the file is never opened.
        assert!(!store.path().exists());
    }

    #[test]
    fn test_populate_cap_counts_unique_keys_not_records() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // 2 * MAX_UNIQUE_KEYS records, MAX_UNIQUE_KEYS unique keys.
        let mut records: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS)
            .map(|i| (format!("k{i}"), "a".to_string()))
            .collect();
        records.extend(
            (0..MAX_UNIQUE_KEYS).map(|i| (format!("k{i}"), "b".to_string())),
        );

        store.populate(records).unwrap();
        assert_eq!(store.len().unwrap(), 2 * MAX_UNIQUE_KEYS);
    }

    #[test]
    fn test_populate_then_insert_respects_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        store.populate(records).unwrap();

        let err = store.insert("overflow", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));

        // Overwriting an existing key at the cap still works.
        store.insert("k0", "updated").unwrap();
        assert_eq!(store.read("k0").unwrap(), Some("updated".to_string()));
    }

    #[test]
    fn test_len_and_is_empty() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(store.is_empty().unwrap());
        assert_eq!(store.len().unwrap(), 0);

        store.insert("key", "value").unwrap();
        assert!(!store.is_empty().unwrap());
        assert_eq!(store.len().unwrap(), 1);

        store.insert("key2", "value2").unwrap();
        assert_eq!(store.len().unwrap(), 2);

        store.insert("key", "updated").unwrap();
        assert_eq!(store.len().unwrap(), 2);
    }

    #[test]
    fn test_is_stale_and_is_stale_at_boot_helpers() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("key", "value").unwrap();

        assert!(!store.is_stale().unwrap());
        assert!(store.is_stale_at_boot(i64::MAX).unwrap());
        assert!(!store.is_stale_at_boot(0).unwrap());
    }

    #[test]
    fn test_is_stale_missing_file_returns_false() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(!store.is_stale().unwrap());
    }

    #[test]
    fn test_clear_if_stale_noop_when_fresh() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("key", "value").unwrap();

        store.clear_if_stale().unwrap();
        assert_eq!(store.read("key").unwrap(), Some("value".to_string()));
    }

    #[test]
    fn test_clear_if_stale_clears_stale_data() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("key", "value").unwrap();
        assert!(!store.is_empty().unwrap());

        set_mtime_to_epoch(store.path());
        assert!(store.is_stale().unwrap());

        store.clear_if_stale().unwrap();
        assert!(store.is_empty().unwrap());
    }

    #[test]
    fn test_encode_decode_round_trip() {
        let record = encode_record("hello", "world");
        assert_eq!(record.len(), RECORD_SIZE);

        let (k, v) = decode_record(&record).unwrap();
        assert_eq!(k, "hello");
        assert_eq!(v, "world");
    }

    #[test]
    fn test_encode_decode_max_length_key() {
        let key = "x".repeat(WIRE_MAX_KEY_BYTES);
        let record = encode_record(&key, "val");
        let (k, v) = decode_record(&record).unwrap();
        assert_eq!(k, key);
        assert_eq!(v, "val");
    }

    #[test]
    fn test_encode_decode_empty_value() {
        let record = encode_record("key", "");
        let (k, v) = decode_record(&record).unwrap();
        assert_eq!(k, "key");
        assert_eq!(v, "");
    }

    #[test]
    fn test_decode_wrong_size_errors() {
        let err = decode_record(&[0u8; RECORD_SIZE + 1]).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::Other);
    }

    #[test]
    fn test_iter_yields_all_records_in_order() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let expected =
            pairs([("a", "1"), ("b", "2"), ("c", "3"), ("d", "4"), ("e", "5")]);
        store.populate(expected.clone()).unwrap();

        let iter = store.iter().unwrap();
        assert_eq!(iter.record_count(), 5);

        let records: Vec<(String, String)> = iter.map(|r| r.unwrap()).collect();
        assert_eq!(records, expected);
    }

    #[test]
    fn test_iter_empty_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        File::create(store.path()).unwrap();

        let iter = store.iter().unwrap();
        assert_eq!(iter.record_count(), 0);
        assert_eq!(iter.count(), 0);
    }

    #[test]
    fn test_iter_malformed_file_error() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        std::fs::write(store.path(), [0u8; RECORD_SIZE + 1]).unwrap();

        let err = store.iter().unwrap_err();
        assert!(matches!(err, KvpError::Io(_)));
    }

    #[test]
    fn test_iter_drop_mid_iteration_releases_lock() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("k1", "v1"), ("k2", "v2")])).unwrap();

        {
            let mut iter = store.iter().unwrap();
            iter.next().unwrap().unwrap();
        }

        store.insert("k3", "v3").unwrap();
        assert_eq!(store.len().unwrap(), 3);
    }

    #[test]
    fn test_overwrite_adjacent_records_untouched() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([
                ("first", "val_first"),
                ("middle", "val_middle"),
                ("last", "val_last"),
            ]))
            .unwrap();

        let raw_before = std::fs::read(store.path()).unwrap();
        let first_before = &raw_before[..RECORD_SIZE];
        let last_before = &raw_before[2 * RECORD_SIZE..3 * RECORD_SIZE];

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            let (k, _) = iter.next().unwrap().unwrap();
            assert_eq!(k, "middle");
            iter.overwrite_current_value("UPDATED").unwrap();
            iter.flush().unwrap();
        }

        let raw_after = std::fs::read(store.path()).unwrap();
        assert_eq!(&raw_after[..RECORD_SIZE], first_before);
        assert_eq!(&raw_after[2 * RECORD_SIZE..3 * RECORD_SIZE], last_before);

        assert_eq!(
            store.dump().unwrap(),
            pairs([
                ("first", "val_first"),
                ("middle", "UPDATED"),
                ("last", "val_last"),
            ])
        );
    }

    #[test]
    fn test_overwrite_multiple_in_one_pass() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "old_a"), ("b", "old_b"), ("c", "old_c")]))
            .unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            let mut idx = 0;
            while let Some(record) = iter.next() {
                record.unwrap();
                if idx == 0 || idx == 2 {
                    iter.overwrite_current_value("new").unwrap();
                }
                idx += 1;
            }
            iter.flush().unwrap();
        }

        assert_eq!(
            store.dump().unwrap(),
            pairs([("a", "new"), ("b", "old_b"), ("c", "new")])
        );
    }

    #[test]
    fn test_overwrite_before_next_errors() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("k", "v").unwrap();

        let mut iter = store.iter_mut().unwrap();
        let err = iter.overwrite_current_value("new").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidInput);
    }

    #[test]
    fn test_remove_before_next_errors() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("k", "v").unwrap();

        let mut iter = store.iter_mut().unwrap();
        let err = iter.remove_current().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidInput);
    }

    #[test]
    fn test_remove_swap_and_continue() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("A", "1"), ("B", "2"), ("C", "3"), ("D", "4")]))
            .unwrap();

        let mut collected = Vec::new();
        {
            let mut iter = store.iter_mut().unwrap();
            while let Some(record) = iter.next() {
                let (k, v) = record.unwrap();
                if k == "B" {
                    iter.remove_current().unwrap();
                } else {
                    collected.push((k, v));
                }
            }
            iter.flush().unwrap();
        }

        assert_eq!(collected.len(), 3);
        assert!(collected.iter().any(|(k, _)| k == "A"));
        assert!(collected.iter().any(|(k, _)| k == "C"));
        assert!(collected.iter().any(|(k, _)| k == "D"));

        assert_eq!(store.len().unwrap(), 3);
        assert_eq!(store.read("B").unwrap(), None);
    }

    #[test]
    fn test_remove_last_record_no_swap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "1"), ("b", "2"), ("c", "3")]))
            .unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            iter.next().unwrap().unwrap();
            iter.next().unwrap().unwrap();
            iter.remove_current().unwrap();
            iter.flush().unwrap();
        }

        assert_eq!(store.len().unwrap(), 2);
        assert_eq!(store.read("c").unwrap(), None);
        assert_eq!(store.read("a").unwrap(), Some("1".to_string()));
        assert_eq!(store.read("b").unwrap(), Some("2".to_string()));
    }

    #[test]
    fn test_remove_only_record() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("solo", "val").unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            iter.remove_current().unwrap();
            iter.flush().unwrap();
        }

        assert!(store.is_empty().unwrap());
    }

    #[test]
    fn test_file_integrity_after_mixed_ops() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        for i in 0..10 {
            store.insert(&format!("u{i}"), &format!("uv{i}")).unwrap();
        }
        for i in 0..5 {
            store.append(&format!("a{i}"), &format!("av{i}")).unwrap();
        }
        store.delete("u3").unwrap();
        store.delete("u7").unwrap();
        store.insert("u0", "overwritten").unwrap();

        let raw = std::fs::read(store.path()).unwrap();
        assert_eq!(raw.len() % RECORD_SIZE, 0);

        let record_count = raw.len() / RECORD_SIZE;
        for i in 0..record_count {
            let start = i * RECORD_SIZE;
            let end = start + RECORD_SIZE;
            decode_record(&raw[start..end]).unwrap();
        }
    }

    #[test]
    fn test_kvp_error_display() {
        let cases: Vec<(KvpError, &str)> = vec![
            (KvpError::EmptyKey, "KVP key must not be empty"),
            (
                KvpError::Io(io::Error::new(ErrorKind::NotFound, "gone")),
                "gone",
            ),
            (
                KvpError::KeyContainsNull,
                "KVP key must not contain null bytes",
            ),
            (
                KvpError::KeyTooLarge {
                    max: 254,
                    actual: 300,
                },
                "KVP key length (300) exceeds maximum (254)",
            ),
            (
                KvpError::MaxUniqueKeysExceeded { max: 1024 },
                "KVP unique key count exceeded maximum (1024)",
            ),
            (
                KvpError::ValueTooLarge {
                    max: 1022,
                    actual: 2000,
                },
                "KVP value length (2000) exceeds maximum (1022)",
            ),
        ];
        for (err, expected) in cases {
            assert_eq!(err.to_string(), expected);
        }
    }

    #[test]
    fn test_kvp_error_source() {
        let io_err = KvpError::Io(io::Error::other("kvp-error-source"));
        assert!(io_err.source().is_some());

        assert!(KvpError::EmptyKey.source().is_none());
        assert!(KvpError::KeyContainsNull.source().is_none());
    }

    #[test]
    fn test_kvp_error_from_io() {
        let io_err = io::Error::new(ErrorKind::PermissionDenied, "denied");
        let kvp_err: KvpError = io_err.into();
        assert!(matches!(kvp_err, KvpError::Io(_)));
        assert_eq!(kvp_err.to_string(), "denied");
    }

    #[test]
    fn test_concurrent_inserts_to_different_keys() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        let key = format!("t{t}_k{i}");
                        store.insert(&key, &format!("val_{t}_{i}")).unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 80);
        for t in 0..8 {
            for i in 0..10 {
                let key = format!("t{t}_k{i}");
                assert_eq!(entries.get(&key), Some(&format!("val_{t}_{i}")));
            }
        }
    }

    #[test]
    fn test_concurrent_inserts_to_same_key() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        store
                            .insert("shared_key", &format!("t{t}_v{i}"))
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        assert_eq!(store.len().unwrap(), 1);
        let val = store.read("shared_key").unwrap().unwrap();
        assert!(val.starts_with('t') && val.contains("_v"));

        let file_len = std::fs::metadata(store.path()).unwrap().len() as usize;
        assert_eq!(file_len, RECORD_SIZE);
    }

    #[test]
    fn test_concurrent_appends() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        store
                            .append(
                                &format!("t{t}_d{i}"),
                                &format!("data_{t}_{i}"),
                            )
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        assert_eq!(store.len().unwrap(), 80);

        let entries = store.entries().unwrap();
        for t in 0..8 {
            for i in 0..10 {
                let key = format!("t{t}_d{i}");
                assert!(entries.contains_key(&key), "missing key {key}");
            }
        }
    }

    #[test]
    fn test_concurrent_writers_at_key_cap() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        prepopulate(&store, MAX_UNIQUE_KEYS - 4);

        let threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    store.insert(&format!("new{t}"), "v")
                })
            })
            .collect();

        let results: Vec<_> =
            threads.into_iter().map(|t| t.join().unwrap()).collect();

        let successes = results.iter().filter(|r| r.is_ok()).count();
        let cap_errors = results
            .iter()
            .filter(|r| {
                matches!(r, Err(KvpError::MaxUniqueKeysExceeded { .. }))
            })
            .count();

        assert_eq!(successes, 4);
        assert_eq!(cap_errors, 0);
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        let err = store.insert("one_too_many", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));
    }

    #[test]
    fn test_concurrent_readers_only() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        for i in 0..10 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|_| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for _ in 0..20 {
                        let entries = store.entries().unwrap();
                        assert_eq!(entries.len(), 10);
                        for i in 0..10 {
                            assert_eq!(
                                store.read(&format!("k{i}")).unwrap(),
                                Some(format!("v{i}"))
                            );
                        }
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }
    }

    #[test]
    fn test_concurrent_readers_and_writers() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        for i in 0..10 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let writer_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for round in 0..5 {
                        let key = format!("k{t}");
                        store.insert(&key, &format!("w{t}_r{round}")).unwrap();
                    }
                })
            })
            .collect();

        let reader_threads: Vec<_> = (0..4)
            .map(|_| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for _ in 0..20 {
                        let entries = store.entries().unwrap();
                        assert!(entries.len() <= 10);
                        for (k, v) in &entries {
                            assert!(!k.is_empty());
                            assert!(!v.is_empty());
                        }
                    }
                })
            })
            .collect();

        for t in writer_threads {
            t.join().unwrap();
        }
        for t in reader_threads {
            t.join().unwrap();
        }

        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 10);
    }

    #[test]
    fn test_concurrent_mixed_insert_and_append() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        for i in 0..4 {
            store.insert(&format!("fixed{i}"), "init").unwrap();
        }

        let insert_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for round in 0..5 {
                        store
                            .insert(&format!("fixed{t}"), &format!("r{round}"))
                            .unwrap();
                    }
                })
            })
            .collect();

        let append_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..5 {
                        store
                            .append(
                                &format!("diag_t{t}_i{i}"),
                                &format!("d{i}"),
                            )
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in insert_threads {
            t.join().unwrap();
        }
        for t in append_threads {
            t.join().unwrap();
        }

        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 24);
        for t in 0..4 {
            assert!(entries.contains_key(&format!("fixed{t}")));
        }
    }

    #[derive(Clone, Copy)]
    enum StoreOp {
        Read,
        Delete,
        Clear,
        Entries,
        Dump,
        Populate,
        Len,
        IsStale,
        IsStaleAtBoot,
    }

    /// Every fallible read/write op surfaces an unreachable directory
    /// as [`KvpError::Io`].
    #[rstest]
    #[case::read(StoreOp::Read)]
    #[case::delete(StoreOp::Delete)]
    #[case::clear(StoreOp::Clear)]
    #[case::entries(StoreOp::Entries)]
    #[case::dump(StoreOp::Dump)]
    #[case::populate(StoreOp::Populate)]
    #[case::len(StoreOp::Len)]
    #[case::is_stale(StoreOp::IsStale)]
    #[case::is_stale_at_boot(StoreOp::IsStaleAtBoot)]
    fn test_permission_denied(#[case] op: StoreOp) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k", "v").unwrap();

        lock_dir(dir.path());
        let result: Result<(), KvpError> = match op {
            StoreOp::Read => store.read("k").map(|_| ()),
            StoreOp::Delete => store.delete("k").map(|_| ()),
            StoreOp::Clear => store.clear(),
            StoreOp::Entries => store.entries().map(|_| ()),
            StoreOp::Dump => store.dump().map(|_| ()),
            StoreOp::Populate => store.populate(pairs([("a", "b")])),
            StoreOp::Len => store.len().map(|_| ()),
            StoreOp::IsStale => store.is_stale().map(|_| ()),
            StoreOp::IsStaleAtBoot => {
                store.is_stale_at_boot(i64::MAX).map(|_| ())
            }
        };
        unlock_dir(dir.path());
        assert!(matches!(result.unwrap_err(), KvpError::Io(_)));
    }

    #[test]
    fn test_is_stale_at_boot_missing_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        assert!(!store.is_stale_at_boot(i64::MAX).unwrap());
    }

    /// F_WRLCK needs a writable fd; read-only fd returns EBADF.
    #[test]
    fn test_fcntl_lock_exclusive_fails_on_read_only_fd() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().read(true).open(tmp.path()).unwrap();
        let err = fcntl_lock_exclusive(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));
    }

    /// F_RDLCK needs a readable fd; write-only fd returns EBADF.
    #[test]
    fn test_fcntl_lock_shared_fails_on_write_only_fd() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().write(true).open(tmp.path()).unwrap();
        let err = fcntl_lock_shared(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));
    }

    /// FIFO at the pool path: `ftruncate` fails with EINVAL on
    /// a FIFO, verifying that `clear()` propagates the I/O error.
    #[test]
    fn test_clear_truncate_error_on_fifo() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        let c_path =
            std::ffi::CString::new(store.path().as_os_str().as_encoded_bytes())
                .unwrap();
        assert_eq!(unsafe { libc::mkfifo(c_path.as_ptr(), 0o644) }, 0);
        let err = store.clear().unwrap_err();
        assert!(
            matches!(err, KvpError::Io(ref e) if e.raw_os_error() == Some(libc::EINVAL))
        );
    }

    /// FIFO at the pool path: `lseek` fails with ESPIPE inside
    /// `KvpPoolIter::new`, verifying that `append()` propagates it.
    #[test]
    fn test_append_seek_error_on_fifo() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        let c_path =
            std::ffi::CString::new(store.path().as_os_str().as_encoded_bytes())
                .unwrap();
        assert_eq!(unsafe { libc::mkfifo(c_path.as_ptr(), 0o644) }, 0);
        let err = store.append("k", "v").unwrap_err();
        assert!(
            matches!(err, KvpError::Io(ref e) if e.raw_os_error() == Some(libc::ESPIPE))
        );
    }

    /// FIFO at the pool path: ESPIPE surfaces from `KvpPoolIter::new`
    /// before the truncate/rewrite phase.
    #[test]
    fn test_populate_seek_error_on_fifo() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        let c_path =
            std::ffi::CString::new(store.path().as_os_str().as_encoded_bytes())
                .unwrap();
        assert_eq!(unsafe { libc::mkfifo(c_path.as_ptr(), 0o644) }, 0);
        let err = store.populate(pairs([("k", "v")])).unwrap_err();
        assert!(
            matches!(err, KvpError::Io(ref e) if e.raw_os_error() == Some(libc::ESPIPE))
        );
    }

    #[test]
    fn test_decode_record_invalid_utf8_key() {
        let mut buf = vec![0u8; RECORD_SIZE];
        buf[0] = 0xFF;
        buf[1] = 0xFE;
        let err = decode_record(&buf).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidData);
    }

    #[test]
    fn test_decode_record_invalid_utf8_value() {
        let mut buf = vec![0u8; RECORD_SIZE];
        // Key region is valid (all zeros = empty after trim).
        // Put invalid UTF-8 in the value region.
        buf[WIRE_MAX_KEY_BYTES] = 0xFF;
        buf[WIRE_MAX_KEY_BYTES + 1] = 0xFE;
        let err = decode_record(&buf).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidData);
    }

    #[test]
    fn test_size_hint_tracks_iteration() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "1"), ("b", "2"), ("c", "3")]))
            .unwrap();

        let mut iter = store.iter().unwrap();
        assert_eq!(iter.size_hint(), (3, Some(3)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (2, Some(2)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (1, Some(1)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (0, Some(0)));

        assert!(iter.next().is_none());
    }

    /// Covers the `Err(e) => Some(Err(e))` branch in `Iterator::next`
    /// by truncating the file after the iterator caches its record count.
    #[test]
    fn test_iter_read_error_on_truncated_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("a", "1"), ("b", "2")])).unwrap();

        // Open a mutable iterator (exclusive lock) so we can manipulate the file.
        let mut iter = store.iter_mut().unwrap();
        assert_eq!(iter.record_count(), 2);

        // Read the first record successfully.
        let (k, _) = iter.next().unwrap().unwrap();
        assert_eq!(k, "a");

        // Truncate via the iterator's own file to remove the second record.
        // The iterator still thinks record_count == 2, so the next
        // read_exact will hit an unexpected EOF.
        iter.file.set_len(0).unwrap();

        // The iterator's cached record_count (2) > current_index (1),
        // so it attempts read_exact, which fails.
        let err = iter.next().unwrap().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::UnexpectedEof);
    }
}
